controllers:
    resource: ../../src/Controller/*
    type: annotation
    exclude: '../../src/Controller/{Api, Admin}'

api_controllers:
    resource: ../../src/Controller/Api/*
    type: annotation
    prefix: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
